name: THIAGO
favicon: null
layout_spectrum: 0.9054414415732026
typography_spectrum: 0.2255178289487958
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f69601'
    - '#7739c8'
    - '#148fb9'
    - '#f2f2f2'
    - '#000000'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
