name: THIAGO
favicon: null
layout_spectrum: 0.9054414415732026
typography_spectrum: 0.2255178289487958
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.18798190006054938
  lightness: 0.2156517691910267
  saturation: 0.9905629651620984
  rhythmicContrast: 0.7625413399655372
purpose: []
